baseURL = "https://unixdaddy.github.io/kubernetes-workshop-source/"
languageCode = "en-us"
title = "kubernetes workshop"
theme = "hugo-theme-learn"
uglyurls = true
relativeURLs = false
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "blue"
landingPageURL = "/kubernetes-workshop-source/en"
landingPageName = "<i class='fas fa-home'></i> Home"
