baseURL = "https://unixdaddy.github.io/kubernetes-workshop/"
languageCode = "en-us"
title = "kubernetes workshop"
theme = "hugo-theme-learn"
uglyurls = true
relativeURLs = true
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "blue"
